language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
  - pip install pycodestyle
  - pip install termcolor
  - pip install .
  - apt install wkhtmltopdf
script:
  - cd rss_reader
  - nosetests --cover-branches --with-coverage --cover-min-percentage=50 --cover-package=rss_reader
  - pycodestyle --max-line-length=120 .
  - python ./../rss_reader_checker.py
  - cd -

